version: '3.7'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    environment:
      NEO4J_AUTH: neo4j/password
